Feature/d serie 2023 2 msl 2289
Deltares/GEOLib pull request #138
Opened 2023-08-21 09:52 UTC by zantDelta

2023-08-21 12:32 UTC, carloslubbers commented
@zantDelta Are all the .sli files needed in the repository? They weren't there before and now this PR adds a large amount of new files

2023-08-24 08:44 UTC, VirginieTrompille requested changes

2023-08-24 11:46 UTC, zantDelta commented
> 

Yes we parse all our benchmarks and tutorials input files (sli) and output files (sld) like for DFoundations and DSheetPiling

2023-08-24 11:47 UTC, VirginieTrompille commented
Review OK.
Code smell (1) has been solved in other pull request (#137)
Failing tests in TC project Acceptance (GEOLib) are expected because run with old executable. As all tests in project Test (DSerie 2023) pass, it is OK.

2023-08-24 11:48 UTC, VirginieTrompille commented
Pull request accepted even if Code smell and failing tests:
- Code smell (1) has been solved in other pull request (https://github.com/Deltares/GEOLib/pull/137)
- Failing tests in TC project Acceptance (GEOLib) are expected because run with old executable. As all tests in project Test (DSerie 2023) pass, it is OK.

2023-08-24 11:48 UTC, merged